### ISSUE TITLE
Support for saving dependencies

### ISSUE THREAD

**Issue by jdreux** [chlorinejs/lein-bower#14]
Would love to be able to save dependencies from the command line - it's one of best features of bower IMO!

Example: `lein bower install bootstrap --save` would fetch the dependency but also add it to the `project.clj`. Is this possible in the current state of affairs? If not I would love to submit a pull request, provided I get some direction.

**Comment by hackeryarn** [comment]
I don't think this goes well with how Clojure/ClojureScript projects dependencies are managed in general, and I would like to stick to a consistent paradigm.

 I am closing as this is something we most likely will not implement.
